version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./app
    container_name: fastapi_app
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/code

volumes:
  postgres_data:

